#!/bin/bash

set -e
set -x

rm -rf build
mkdir build
pushd build

conan install .. --build=missing
# conan install .. --build=missing -r=demo-conan-virtual -pr ./my_profile

# .. ->  source code, CMakeLists.txt
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_MODULE_PATH=$PWD
cmake --build .

# not bin/md5
./md5


# if cmake in confile.txt
# CMakeLists.txt -> conanbuildinfo.cmake

# if cmake_find_package in confile.txt
# CMakeLists.txt -> find_package(Boost ... regex) -> search FindBoost.cmake (generated by cmake_find_package) in $CMAKE_MODULE_PATH
# so need to copy FindBoost.cmake to $PWD & set –DCMAKE_MODULE_PATH=$PWD
# https://docs.conan.io/en/latest/integrations/build_system/cmake/cmake_find_package_generator.html
